let response = {
  resource: '/',
  path: '/',
  httpMethod: 'GET',
  headers: None,
  multiValueHeaders: None,
  queryStringParameters: None,
  multiValueQueryStringParameters: None,
  pathParameters: None,
  stageVariables: None,
  requestContext: {
    resourceId: 'k2rizpxtsl',
    resourcePath: '/',
    httpMethod: 'GET',
    extendedRequestId: 'QX4IqGbICYcFauQ=',
    requestTime: '23/Dec/2023:01:39:03 +0000',
    path: '/',
    accountId: '591340197826',
    protocol: 'HTTP/1.1',
    stage: 'test-invoke-stage',
    domainPrefix: 'testPrefix',
    requestTimeEpoch: 1703295543196,
    requestId: 'c624ac16-edd3-497f-8d3b-dc5cfc31bf8a',
    identity: {
      cognitoIdentityPoolId: None,
      cognitoIdentityId: None,
      apiKey: 'test-invoke-api-key',
      principalOrgId: None,
      cognitoAuthenticationType: None,
      userArn: 'arn:aws:iam::591340197826:user/frederick',
      apiKeyId: 'test-invoke-api-key-id',
      userAgent:
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15',
      accountId: '591340197826',
      caller: 'AIDAYTLU7K7BGOYJPTQOP',
      sourceIp: 'test-invoke-source-ip',
      accessKey: 'ASIAYTLU7K7BJQATCY52',
      cognitoAuthenticationProvider: None,
      user: 'AIDAYTLU7K7BGOYJPTQOP',
    },
    domainName: 'testPrefix.testDomainName',
    apiId: 'mmqchcjl10',
  },
  body: None,
  isBase64Encoded: False,
};
